LineLength:
  Max: 120

Style/Next:
  Enabled: false

Documentation:
  Enabled: false

MethodLength:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/ClassLength:
  Max: 150

Style/FileName:
  Exclude:
    - bin/chefspec-bootstrap

Lint/UselessAssignment:
  Exclude:
    - lib/chefspec_bootstrap.rb
